### PR TITLE
Nicer automated snapshot of files from Verus + weekly auto-updates

### PR DESCRIPTION
**Pull request by jaybosamiya**
This PR does a few things:

- Moves away from the older snapshot of vstd (that collapsed all of vstd to a single file using [inline-crate](https://github.com/jaybosamiya/inline-crate/)) to instead hold each file individually
- Sets up a script that makes it easy to get the latest vstd from Verus (and also a helper script to format it)
- Moves `syntax.rs` to be part of this automatically-get-this-from-Verus setup
- Updates the snapshot tests to account for this move
- Sets up a CI job that runs once every night (at UTC 00:00) to see if our snapshot has diverged from Verus's. If it has, then it opens up a PR to call our attention to it

To review this PR, it is likely easiest to look at each commit individually.

NOTE: This PR should not be merged into verusfmt `main` until https://github.com/verus-lang/verus/pull/1019 and an upcoming PR for `syntax.rs` have been merged. Thus, I am marking it as a draft, despite otherwise being ready to review.

### CODE REVIEW

**Review by parno — APPROVED** [review]
Thanks, this looks like a nice way to keep things in sync, which will make it easier to detect possibly "breaking" changes to vstd (or other Verus files).

However, I'd be inclined to set the CI job to run once a week/month.  I suspect there'll be enough churn in `vstd` that getting a PR about it each time will be a bit of a nuisance, and I'd be surprised if most of that churn was of a nature that would cause `verusfmt` changes to be needed.

**Comment by jaybosamiya** [comment]
Sounds reasonable, switched it to weekly, and if even that ends up too much, we can switch it out to monthly

**Comment by jaybosamiya** [comment]
Now that https://github.com/verus-lang/verus/pull/1019 is merged, we can merge this in. I will then manually trigger the workflow run (outside regular schedule, just to confirm it is working as expected), but after that, the weekly schedule should begin.

**Comment by jaybosamiya** [comment]
Heh, it detects the difference correctly (the part that I had tested before making the PR), but doesn't actually make the PR (the part that I could not test earlier). Turns out that this is because of an organization level permission:
> For repositories belonging to an organization, this setting can be managed by admins in organization settings under Actions > General > Workflow permissions.

Will work on getting that set up, so that this starts working

**Pull request merged**
